# The URL the site will be built for
base_url = "https://rua.plus"
title = "xfy"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
minify_html = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
[markdown.highlighting]
theme = "catppuccin-mocha"
# highlight_code = true
# highlight_theme = "css"
# highlight_themes_css = [
#   { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
#   { theme = "ayu-light", filename = "syntax-theme-light.css" },
# ]

[extra]
theme = "toggle"
socials = [
  { name = "twitter", url = "https://twitter.com/Defect__", icon = "twitter" },
  { name = "github", url = "https://github.com/DefectingCat", icon = "github" },
  { name = "rss", url = "/atom.xml", icon = "rss" },
]
menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/tags", url = "/tags", weight = 2 },
]
toc = true
use_cdn = false
fancy_code = true
comment = false
favicon = "/images/favicon.webp"

[extra.analytics]
enabled = false
